backend/pzserver/settings.py
env_template

Adicionei uma condição no settings.py para só habilitar o github oauth caso a variavel SOCIAL_AUTH_GITHUB_ORG_KEY tenha valor. 
Deixei no env_template a variavel comentada por default. isso é para facilicar o ambiente do desenvolvedor que não precisar ter o OAuth configurado e também o ambiente de testes automatizados. 
**Importante** Alterei as variaveis de config do banco, substitui SQL_ por DB_ só para ficar igual aos outros apps.

Added condition that makes OAuth authentication optional

---

backend/core/admin.py
backend/core/models/product.py
backend/core/serializers/__init__.py
backend/core/serializers/release.py
backend/core/serializers/user.py
backend/core/views/__init__.py
backend/core/views/product.py
backend/core/views/user.py
backend/pzserver/urls.py

- Adicionado endpoint que retorna os usernames
- Adicionado filtro por username, first_name, last_name no endpoint de produtos. 
- Adicionado username, first_name, last_name na search de produtos. 
Exemplos:
Endpoint Users: 
http://localhost/api/users/
Filtro por usuario na lista de produtos. 
A busca considera o valor passado no parametro uploaded_by como uma query like case insensitive.  
algo como username ilike  %param% OR first_name ilike %param% OR last_name ilike %param%
Exemplos: 
Considerando nome de usuário gverde:
http://localhost/api/products/?uploaded_by=gverde
http://localhost/api/products/?uploaded_by=g
http://localhost/api/products/?uploaded_by=erde
Procurar produtos de um usuario usando Search (Interface ou API)
http://localhost/api/products/?search=gverde
Neste caso o …

Added filter by user in product endpoint

---

.github/workflows/push_docker_images.yml

Adicionando novas tags _dev_latest para serem usadas de forma automática nos  ambientes de dev. estas tags vão apontar sempre para a versão mais recente no branch main

Added  new docker tag _dev_latest

---

README.md
backend/core/test/test_product.py
backend/core/test/test_product_content.py
backend/core/test/test_product_file.py
backend/core/views/product.py

duas causas para os erros nos testes: 
- A regra que valida o campo survey estava invertida na view, deveria permitir o campo survey apenas para produtos do tipo specz_catalog.
- Após a troca da lista inicial de product types, alguns testes pararam de funcionar por que usavam o primeiro product type que a query retornava, como a ordem mudou os campos que estavam sendo usados para o produto passaram a ser invalidos para o tipo de produto, exemplo campo release em um product type que não deveria. a solução foi deixar fixo os product types usados nos testes. 
Se os testes passarem o PR está valido.

Fixed #100 - Backend unit tests

---

frontend/pages/about.js

@gschwend já existia um link para este documento mas  estava no parenteses todo 
desta forma: ( [ see technical note dmtn-049 for details](https://dmtn-049.lsst.io/) )
eu alterei e deixei só o nome do arquivo agora. 
ficou assim: (see technical note [dmtn-049](https://dmtn-049.lsst.io/) for details)

Closed #93 - Add link to document in About page

---

README.md
backend/core/product_handle.py
backend/core/test/test_product_handle.py
backend/core/test/util.py
nginx_development.conf

The reading of catalogs with undefined extension and format was implemented. instead of returning an exception the catalog will be read using numpy loadtxt. #92
Added TxtHandle class in product_handle. 
- Try read table using numpy.loadtxt
- Ignore all lines start with #
- ignores all initial lines that after the split have only string.
- Acept space as delimiter.
- Does not accept string values.
- If it is identified that it has only one header line, it tries to generate the columns from it. if there are multiple lines in the header, they will all be ignored and the columns will have a sequential name.

Suport plain text catalogs

---

frontend/components/Header.js
frontend/components/ProductGrid.js
frontend/pages/_app.js

persist the last theme chosen by the user. Now when the user chooses a theme, it will be saved in his browser, so that every time he accesses the **PZ-SERVER**, his preferred theme will already be selected.
fixed the way the 'share' function was getting the download url.
To test it out, just pull the '`final-adjustments`' branch in your development environment.

Fix dark-theme and share-button

---

frontend/pages/oficial_products.js

Was changed **official-products** title from '_LSST PZ Data Products_' -> '_Rubin Observatory PZ Data Products_'
To perform a test, access the PZ-SERVER and open the Official Data Products card. You'll notice that the title now matches the selected card.

Closed #176 was changed official-products title

---

frontend/components/ProductDetail.js
frontend/pages/product/new.js

Fixed a small bug on the **product details** page where the file name was sticking out of the card on smaller screens.
Then in **Step3**, the name of the label that was inverted was adjusted. Association Columns > Association Columns.

Layout adjustment

---

frontend/components/ProductDetail.js

A tab next to the table preview was implemented, where now, when there are files with an .html extension, a 'Description Html' tab next to 'Table Preview' will be displayed, where it will render by default the content generated through the url of the .html.

A tab next to the table preview was implemented

---

frontend/components/ProductDataGrid.js

Now, while the `table preview` file is loaded, the message 'Loading...' is displayed instead of 'No rows'

Closes #199 - Now, when loading a file in table preview, a 'Loading...' message will appear.

---

frontend/components/ProductDetail.js
frontend/components/newProduct/Step4.js

Fixed the error that was occurring when trying to upload a .pq file. 
the error was being caused due to trying to access `res.response.status` directly after a `.catch()` without checking if the `response` property exists in the error object.

Fixes #187 - fixed the error that was occurring when trying to upload

---

backend/core/models/product.py
backend/core/serializers/product.py
backend/core/test/test_product.py
backend/core/views/product.py
frontend/components/ProductGrid.js
frontend/components/ProductRemove.js

1. Users with common privileges can now only delete their own records, while administrators retain the ability to delete any record. The DeleteIcon is intelligently disabled for products owned by other users, while it remains active for administrators.
2. Was added an informative hover message to the DeleteIcon. Now, when you hover your mouse over the icon, you'll receive context-aware feedback:
- If you're the owner of the record, you'll receive a positive message.
- If the record doesn't belong to you, you'll receive a negative message.
[Here is a short video demonstrating the features of this update.](https://youtu.be/AzBGGfZzNdI)

Fix! Enhancements in Deletion Functionality

---

frontend/components/ProductFileTextField.js
frontend/components/TokenDialog.js
frontend/pages/oficial_products.js
frontend/pages/product/edit/[pid].js
frontend/pages/product/new.js
frontend/pages/upload.js
frontend/pages/user_products.js

Implemented improved error handling across multiple project files. Error handling messages using `Snackbar` and `Alert` have been added at specific points:
-  `ProductFileTextField.js`, the `handleRemoveFile` function now displays a `Snackbar` in case of an error when removing a file, providing an explanatory message.
-  `TokenDialog.js`, the `generateApiToken` function shows a `Snackbar` in case of an error during token generation, communicating the reason for the error.
-  `upload.js,` the handleSubmit function now displays a `Snackbar` if a product fails to upload, providing an explanatory message.
-  `user_products.js` and `official_products.js`, error messages have been added for problems loading or processing products.
-  `new.js`, the `handleDiscard` function displays a `Snackbar` …

210 error handling for all requests

---

frontend/pages/_app.js
frontend/themes/dark.js
frontend/themes/light.js

was placed in their appropriate folders. `light.js` and `dark.js`

Closes #220 - organization of the themes.

---

frontend/components/ProductGrid.js

Now, when hovering over the product name, the product description will appear. If there is no description available, a message will display indicating that no description is provided.

feat: add tooltip to display_name showing product description

---

frontend/components/ProductDetail.js

This PR addresses the issue of table previews being displayed for non-tabular data types such as .pkl, .pickle, and .tar files. Previously, these files would show an error message in the table preview card. This change ensures that the entire table preview card is hidden for non-tabular data types, improving the user experience.
- Added logic to identify tabular data types, including .csv, .xls, .xlsx, .pq, and .parquet files.
- Modified the `ProductDetail` component to conditionally render the table preview card based on the data type.
- Updated the `loadFiles` function to set the `isTabular` state based on the file types.
- Verified that table previews are displayed correctly for tabular data types.
- Ensured that the table preview card is hidden for non-tabular data types.
- Tested …

Omit Table Preview for Non-Tabular Data Types

---

frontend/components/ProductDetail.js

in products with tabular main file:
in cases where the main file is not tabular, like a .pkl for example:

Number of rows on product details

---

frontend/pages/specz_catalogs.js
frontend/pages/training_set_maker.js

- `SpeczCatalogs`: parquet
- `TrainingSetMaker`: specz
- CSC
- TSM

feat: add output format selection to SpeczCatalogs and TrainingSetMaker components

---

frontend/package.json
frontend/yarn.lock

This commit upgrades the axios dependency to version 1.8.4. This includes a change in the version constraint to allow for future minor and patch updates.

chore: upgrade axios dependency

---

frontend/pages/about.js

Added text justification to the "About" page and masked the support email for better readability and security.

feat: add dynamic email link to About page

---

frontend/pages/contact.js

This PR updates the Contact page to prevent bots from scraping email addresses. Emails are now set dynamically using `useEffect`, making them invisible in the initial HTML. If JavaScript is disabled, a "Loading..." message is shown instead.
- Replaced static emails with `useState` and `useEffect`.
- Emails are now inserted only after the component mounts.
- Improved security without affecting usability.

🔒 Improve email protection against spam bots

---

frontend/package.json
frontend/yarn.lock

The nextjs package was upgraded from v12.1.5 to v12.3.5. This upgrade includes bug fixes, performance improvements, and new features. It is important to keep dependencies up to date to ensure the application is secure and performs optimally.

feat: upgrade nextjs to v12.3.5

---

.devcontainer/devcontainer.json
backend/core/tasks.py
backend/pzserver/settings.py

This commit configures a separate logger for Celery tasks.
- Added a `tasks` logger configuration to `settings.py`, directing logs to a dedicated `tasks.log` file.
- Configured the `tasks` logger to use a rotating file handler with a maximum size of 5MB and 5 backup files.
- Updated the `check_processes` task in `core/tasks.py` to use the `tasks` logger.
- Commented out the devcontainer pre-commit hooks.

feat: configure task-specific logging

---

frontend/pages/login.js

This commit updates the labels of the login buttons on the login page for clarity and to better reflect their intended purpose.
- The "LOGIN WITH CILOGON (RSP ACCOUNT)" button is updated to "LOGIN LSST MEMBERS (RSP ACCOUNT)".
- The "Login with GitHub" button is updated to "LOGIN ADMIN".

feat: update login button labels

---

frontend/components/ProductDetail.js

This commit modifies the ProductDetail component to always display the product description, regardless of whether the product has a release associated with it. The conditional rendering based on `product.release` has been removed, ensuring that the description is consistently visible.

feat: always display product description in ProductDetail

---

frontend/components/ProductDetail.js

This commit modifies the ProductDetail component to display the product type and description consistently.
- Added a "Product Type" field to display the product's type.
- Modified the product description to always display unless an HTML file exists, ensuring consistent visibility.

feat: display product type and description consistently in ProductDetail
