linea-it/pzserver_app

- README.md
- backend/.vscode/settings.json
- backend/core/fixtures/initial_data.yaml
- backend/core/migrations/0001_initial.py
- backend/core/migrations/0002_release_product_description_file_and_more.py
- backend/core/models/__init__.py
- backend/core/models/product.py
- backend/core/models/product_type.py
- backend/core/models/release.py
- backend/core/serializers/__init__.py
- backend/core/serializers/product.py
- backend/core/serializers/product_type.py
- backend/core/serializers/release.py
- backend/core/views/__init__.py
- backend/core/views/github_auth.py
- backend/core/views/product.py
- backend/core/views/product_type.py
- backend/core/views/release.py
- backend/pzserver/urls.py
Changed the project structure, now each model, view and serializer is in an individual file.
A file was created with the initial data, basic for the operation of the application.
> Changed the project structure.

- frontend/pages/about.js
@glaubervila I tried to update the About text including new links. I have no idea how to test it. Please take a look and let me know if it worked.
> Update About page text.

- frontend/components/Header.js
- frontend/pages/_app.js
- frontend/pages/index.js
- frontend/styles/components/Header.js
- frontend/styles/pages/index.js
Closed #19 
Closed #29 
Closed #30 
Closed #31
> Feat/improve UI

- backend/core/views/__init__.py
- backend/core/views/product.py
- backend/core/views/product_type.py
- backend/core/views/release.py
- backend/core/views/user.py
- backend/pzserver/settings.py
- backend/pzserver/urls.py
Get basic token using the endpoint: <hostname>/api/get_token (with authenticated user)
> Created access to API by basic token per authenticated user

- backend/core/views/product.py
To test go to: http://localhost/api/products/<product_id>/content/
> Added endpoint to retrieve content from a csv product.

- frontend/components/newProduct/Step1.js
- frontend/components/newProduct/Step2.js
- frontend/components/newProduct/Step3.js
- frontend/components/newProduct/Step4.js
- frontend/pages/product/new.js
> Added tips in new product interface

- backend/core/_typing.py
- backend/core/product_handle.py
- backend/core/views/product.py
- backend/core/views/registry_product.py
Fixed bug when importing some csv files. Errors related to not being able to identify the headers and the delimiter.
Corrigi o bug que acontecia no upload de alguns arquivos, onde o código falhava para identificar o delimitador ou os headers. 
Provavelmente a causa da falha era alguns valores vazios. nos registros. como a função que identifica o formato precisa ler uma parte do arquivo, se o valor nulo não estivesse nessa parte o erro não acontecia. 
A solução agora usa o pandas para ler o csv. deixando toda a validação e identificação do formato por conta do pandas.read_csv(). acredito que agora deve suportar todos os formatos de csv. 
Aproveitei e implementei o tratamento para csv com ou sem header. agora os sem headers vão ter colunas em sequencia numerica. 
Também iniciei a criação de …
> Fixed bug when importing some csv files. 

- frontend/components/newProduct/Step2.js
https://linea-it.atlassian.net/browse/PZ-112?atlOrigin=eyJpIjoiOWEyOGM1YzdjYjE3NDFmNTlkMTMxYzM5NjE2Y2FmZWYiLCJwIjoiaiJ9
> Removed field for upload description file

- frontend/components/ProductTypeSelect.js
- frontend/components/newProduct/Step1.js
Alterei o componente Select Product Type, adicionando uma propriedade useId (bool) o valor default é true mantendo o comportamento antigo do componente. 
quando useId is false o retorno da função onChange do componente é um objeto contendo os atributos de product_type. 
o campo value do select continua sendo somente o id, nesse caso ao usar essa opção é necessário considerar só o id para value.
> Fixed product type rules in upload form

- backend/core/product_handle.py
- backend/core/views/product.py
- backend/core/views/product_type.py
- backend/core/views/release.py
As viewers Product Type e Release foram protegidas, permitindo delete e update somente pelo admin.
> Corrigido problema com filtros de product_type e release.

- backend/core/fixtures/initial_data.yaml
- backend/core/product_handle.py
- backend/core/test/test_product.py
- backend/core/test/test_product_registry.py
- backend/core/views/product.py
Changed the behavior of the content function to download the file instead of returning the content.
> Content endpoint change

- backend/core/__init__.py
- backend/core/views/product.py
- backend/core/views/product_type.py
- backend/core/views/release.py
- backend/pzserver/settings.py
- backend/pzserver/test_settings.py
to test, use HTTP method "OPTIONS": http://localhost/api/products/api_schema
reference: https://www.django-rest-framework.org/api-guide/metadata/#drf-schema-adapter
> Endpoint created with schema metadata for products

- frontend/components/newProduct/Step2.js
@gschwend Adicionei as informações, mas fiquei na duvida na parte dos Indices se não me engano a gente falou sobre isso, e era uma correção a ser feita na biblioteca, mas eu não tenho certeza. de qualquer forma é fácil alterar.
> Closed #87 - Added more info to the upload instructions

- frontend/components/ProductDetail.js
Removed Download Buttons and Fixed diplay long filename truncate.
> Closed #107 - Removed Download Buttons

- frontend/components/newProduct/Step3.js
Added more columns to be used in association interface.
z (ucd = src.redshift)
z_err (ucd = stat.error;src.redshift)
z_flag (ucd = stat.rank)
survey (ucd = meta.curation)
> Closed #135 - Update column association. 

- frontend/components/ProductDetail.js
Added a rule that only displays the download button when the product status equals 1.
> Closed #143 - Hide download button

- .devcontainer/devcontainer.json
- backend/core/views/product.py
- backend/core/views/product_content.py
- backend/entrypoint.sh
- env_template
- frontend/components/ProductDataGrid.js
- frontend/components/ProductDetail.js
- frontend/package.json
- frontend/pages/_app.js
- frontend/services/product.js
- frontend/yarn.lock
Added a table preview in Product Detail interface. 
Added a new endpoint to read data from product file.
Changed filter name product_id to product in produc_content endpoints.
> Closed #134 - Table preview. 

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .vscode/settings.json
- backend/Dockerfile
- backend/entrypoint.sh
- backend/requirements.txt
- backend/start.sh
- docker-compose-development.yml
- Fix permission in entrypoint
- changed dockerfile not using multiple stages build. 
- updated devcontainer.
Acredito que a forma de validar este branch seja fazendo um novo clone e seguindo os passos da instalação do README. 
Ao fazer o pull do branch main tive problemas de permissão com o arquivo entrypoint. no meu caso não eu não altero o usuário no docker-compose. 
Alterei o comando copy do entripoint para colocar o entrypoint fora da pasta /app pq  identifiquei que era esse o problema.  acho que a copia com chmod estava sendo ignorada pq o arquivo já existia no destino. 
Alterei o script entrypoint para um que aguarda até que o postgresql esteja disponível, e não inicia o servidor web.  
Adicionei um script /start.sh que inicia o servidor web. A vantagem em tirar o servidor web do …
> Changes in dockerfile

- frontend/services/api.js
- frontend/services/product.js
Closed #169 changed default timeout from 5s -> 15s and read_data timeout from 5s -> 2m. Changed the default timeout error message
> Closed #169 changed default timeout

- frontend/components/newProduct/Step3.js
when the user only typed 'space' in the 'alias' option, it was being saved in the database, now I've added a property that will check, if the input contains only space, then nothing will happen in the database.
> added trim on input value

- frontend/components/newProduct/Step3.js
it is now possible to delete all characters from the input alias with backspace.
> Fixed #188 delete last character with backspace

- frontend/components/ProductDetail.js
- frontend/services/api.js
The timeout that was causing the bug when opening the product detail page was increased and the entire ProductDetail file was error handled
> Fixes #208 - Timeout has been increased and error handling.

- frontend/pages/about.js
- frontend/pages/tutorials.js
The URL has been updated successfully!
> Fixes #222 - the URL has been updated successfully!

- frontend/pages/pz_pipelines.js
> Fixes #258 - fixed

- frontend/components/ProductGrid.js
**Fixes #263**
- columns have been adjusted to prevent product names from being hidden on smaller screens.
- action buttons were added in a single column
> Adjust column spacing.

- frontend/components/ProductDataGrid.js
> Pagination removed

- frontend/components/ProductDetail.js
Fixes #275 - changed from router.back to router.push
> Click path changed

- frontend/pages/training_set_maker.js
This PR adds a success dialog box that appears upon submitting a pipeline. The dialog includes a confirmation message and an 'OK' button, which, when clicked, redirects the user to the `'user_products'` page. This enhancement improves user experience by providing immediate feedback on successful submission and a seamless transition to the products page.
> Add success dialog with redirect on pipeline submission

- backend/core/product_handle.py
- backend/core/product_steps.py
When reading 'fits' files using tables_io, incorrectly ordered dictionaries are returned.
> Unexpected return from tables_io library

- frontend/components/ProductDetail.js
- Added logic to the ArrowBackIosIcon component to conditionally navigate to either /user_products or /oficial_products based on the product type.
- Ensured that official products redirect to /oficial_products and user products redirect to /user_products.
> Implement Conditional Navigation for Product Detail Page

- frontend/pages/login.js
> removed the sentence: 'New user? Register here: English or Português'

- frontend/pages/tutorials.js
- add info about Training Results type
- fix broken link to tutorial notebook
- remove unnecessary instructions to install as developer
close #354
> Improvements in Tutorials page

- frontend/components/AlertEnvironment.js
- frontend/pages/_app.js
- frontend/services/api.js
An alert message has been added to all pages informing that the environment is dev (homolog)
> An alert message has been added to all pages informing that the environment is dev (homolog)

- frontend/pages/pz_pipelines.js
> Omit pz-compute card

- backend/core/views/__init__.py
- backend/pzserver/celery.py
- backend/pzserver/settings.py
- backend/pzserver/urls.py
- env_template
- frontend/components/SpeczData.js
- frontend/pages/specz_catalogs.js
- frontend/services/api.js
Clear form button and homologated environment banner
> 364 bugfix clear form button

- frontend/pages/specz_catalogs.js
- frontend/pages/training_set_maker.js
> Feat: added new instruction message on confirm and redirect button

- frontend/components/ProductGrid.js
- frontend/components/ProductRemove.js
- Displaying the product name in the delete confirmation dialog.
- Highlighting the row of the product to be deleted with a distinct background color.
> Enhance delete confirmation with product name and row highlight

- backend/core/serializers/product.py
- backend/core/tasks.py
- backend/core/test/test_product.py
- frontend/components/ProductGrid.js
- frontend/pages/user_products.js
Adding columns Status and Process Status and alteration in header Upload by for Owner
> add status columns to products

- frontend/components/newProduct/Step3.js
Now in column association, UCDs are detailed.
> Show UCD details on name

- frontend/components/ProductRemove.js
Now for known errors we will have a standard message in error handling, and for unknown errors we will have a pop-up like the one in the screenshot below.
> Improve error handling in ProductRemove component

- backend/core/product_steps.py
- backend/core/tasks.py
- backend/core/utils.py
- backend/core/views/process.py
- backend/pzserver/settings.py
- backend/start.sh
- frontend/pages/specz_catalogs.js
- frontend/pages/training_set_maker.js
- frontend/services/product.js
- Implemented mechanism to choose the output format of the pipelines.
- Implemented column mapping to the pipelines output.
- Improved way to save pipeline outputs.
> Implemented column mapping to the pipelines output.

- frontend/components/ProductDetail.js
> Closed #406 - Added message the download is being processed

- frontend/components/Header.js
> Closed #414 - A menu drawer has been added for mobile devices.

- frontend/components/Partnersfooter.js
- frontend/styles/components/Partnersfooter.js
> Fixes:  ESLint warnings

- frontend/components/newProduct/Step4.js
- Added a smoother scroll effect when entering Step 4 for a better user experience.
- Implemented a gradual scrolling animation with easing (easeInOutQuad) for a more natural transition.
- Added a highlight effect on the "Finish" button to draw user attention.
- Ensured the scroll and highlight activate only when the step is loaded.
This improves usability by guiding users directly to the action button in a seamless way
> feat: enhance finish button with smooth scrolling and highlight effect
